### ISSUE TITLE
Tracking: Linux support

### ISSUE THREAD

**Issue by decahedron1** [pykeio/vibe#4]
- [x] Support compiling for Linux with dummy functions
- [ ] Native blur for KWin
- [ ] Blur for GNOME via [Blur my Shell](https://extensions.gnome.org/extension/3193/blur-my-shell/)
